### ISSUE TITLE
snyk.io integration / badge

### ISSUE THREAD

**Issue by jodylecompte** [campDevs/DiscordBot#33]
Snyk is a vulnerability database and monitoring service we can integrate in to ensure that our 3rd party code remains free (as possible) from security vulnerabilities. There is also a badge we can add to the profile.

It's not completely free, but I believe the free tier is more than enough for what we would ever potentially need. It can also be integrated into the CI / CD if we end up setting that up to proactively monitor new depedencies as they are commited in. 

https://snyk.io

**Comment by pahosler** [comment]
integrated into my github, thank you Jody!

**Comment by jodylecompte** [comment]
@glynnw I'm not familar with how Github organizations work, is there a login specifically for the org that would need to be used? It doesn't show up as an option to add from my personal Github account.

**Comment by pahosler** [comment]
I think it would just be attached to the creators account. Alternately, since (I assume everyone is forking <no pun intended>), ppl can self monitor with this. And since most, or some of us, might want to run this (snyk), we will see issues with security reported, if we are keeping up with the master repo, in our forked repo. At that point we can either post an issue or fix it ourselves.
